### ISSUE TITLE
[Request] Ways to wake up the screen without pressing the Power button

### ISSUE THREAD

**Issue by Moxville** [BLumia/pineapple-lock-screen#1]
Pick up motion control (wake device) does not always wake up the screen in my android device

I request for this feature "Double tap to wake (turn on the screen when you double tap it)" 
I found this nice feature in Samsung phone

Thanks for the nice app :)

**Comment by BLumia** [comment]
This is more a ROM level thing and this feature also requires hardware support. If the phone itself has such ability but the ROM doesn't provide such an option, it's likely not possible to provide this feature from an app that doesn't require ROOT.

Luckly, normally you don't need extra apps to do that, most stock ROM have "Tap to wake" option in the settings app located at `Settings -> Display -> Tap to wake`. You can check if your current ROM supports that :)

**Comment by Moxville** [comment]
Thanks a lot for the tip and noted.
