### ISSUE TITLE
Android 13: accessibility setting is grayed when installed from F-droid store

### ISSUE THREAD

**Issue by Attigliuzzo** [BLumia/pineapple-lock-screen#4]
![Screenshot_20230117-075405](https://user-im
I've just installed the app from the f-droid store but I can't enable the accessibility. It says for my security (?), i cannot enable it, why???
I use a custom gsi image called trebledroid (android 13), no gapps, version is 1.2.0 and i use phh SuperSU.
Thanks
![Screenshot_20230117-075405](https://user-images.githubusercontent.com/42100711/212830406-a9f2bc22-8cea-4333-b15a-1806dc34089b.png)

**Comment by BLumia** [comment]
> It says for my security

Who says? Your system? Any screenshot about your current situation?

**Comment by Attigliuzzo** [comment]
Yes, my system.
![Screenshot_20230117-075852](https://user-images.githubusercontent.com/42100711/212830754-65acd232-b0d9-41f0-b8b6-0d06492c4e3a.png)

**Comment by BLumia** [comment]
I googled it a little bit and found this: https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/

And you can manually turn on the "Allow restricted settings" option too: https://support.google.com/android/answer/12623953

**Comment by BLumia** [comment]
Does manually enable "Allow restricted settings" option addressed your issue?

By the way, since this might happens on all apps that requires accessibility service that you downloaded from F-droid, I also reported this to upstream. See: https://gitlab.com/fdroid/fdroidclient/-/issues/2515

**Comment by Attigliuzzo** [comment]
> Does manually enable "Allow restricted settings" option addressed your issue?
> 

Yes, this did the trick. Everytime I forget to check app settings.
Thanks ;)
