### ISSUE TITLE
Lock down mode

### ISSUE THREAD

**Issue by omginput** [BLumia/pineapple-lock-screen#5]
Can I lock down Android with this app without needing to go into the On/Off menu? If not is it possible to implement this?

**Comment by BLumia** [comment]
> Can I lock down Android with this app without needing to go into the On/Off menu?

Sorry I don't understand the question. What is the "On/Off menu" that you referred to? Could you provide a screenshot?

By default, you'll be able to create a shortcut icon to your launcher so you can just click the shortcut to turn off (lock) the screen without entering the main UI screen of the application.

**Comment by BLumia** [comment]
Closing since it's not possible to do with AccessibilityService API.
